DR-2: Optimized DUC-DUCX exchanger (balance check, queue, auto-forwarding, status check)
MyWishPlatform/ducatus_exchange_backend pull request #40
Opened 2021-10-21 12:05 UTC by ddsvetlov

2021-10-21 12:15 UTC, dsahdr commented on ducatus_exchange/ducatus_api.py
> +    tx = parity.transfer(receiver, amount)
Тут ты получается делаешь возврат с общего кошелька, а не с HDWallet

2021-10-21 12:15 UTC, ephdtrg approved these changes
да, норм, единственное что я тут подумал - а там сравнивается баланс и amount, а у нас еще комиссия транзакций есть, которая считается внутри методов transfer_ducatus и transfer_ducatusx, возможно подумать и предусмотреть, чтобы с запасом проверяло

2021-10-21 12:15 UTC, ephdtrg commented on ducatus_exchange/litecoin_rpc.py
> +DUC_DECIMALS = 8
уже есть такое

https://github.com/MyWishPlatform/ducatus_exchange_backend/blob/b7f86e37d904c189d6442f7b888cdb0df31340fa/ducatus_exchange/consts.py#L8

2021-10-21 12:15 UTC, ephdtrg commented on ducatus_exchange/litecoin_rpc.py
> +        return self.rpc.getbalance('') * DUC_DECIMALS
баланс на 8 умножается :)

2021-10-21 12:16 UTC, dsahdr commented on ducatus_exchange/litecoin_rpc.py
> +DUC_DECIMALS = 8
Лежит в ducatus_exchange/consts.py

2021-10-21 12:20 UTC, dsahdr commented on ducatus_exchange/transfers/api.py
> +        )
Отсутствует сохранение в базу хэша возврата, чтобы отображать юзерам

2021-10-21 12:21 UTC, dsahdr commented on ducatus_exchange/transfers/api.py
> +        )
аналогично прошлому комменту

2021-10-21 14:16 UTC, ephdtrg approved these changes
выглядит норм

2021-10-22 11:16 UTC, dsahdr approved these changes

2021-10-22 11:30 UTC, ephdtrg approved these changes

2021-10-25 08:25 UTC, ephdtrg requested changes

2021-10-25 08:25 UTC, ephdtrg commented on ducatus_exchange/start_bot_polling.py
> +
`if __name__ == '__main__':`

2021-10-25 09:29 UTC, ephdtrg approved these changes

2022-01-18 09:39 UTC, yulian-khalitov approved these changes

2022-01-18 09:42 UTC, merged