Dr 125
MyWishPlatform/ducatus_exchange_backend pull request #43
Opened 2021-12-10 16:59 UTC by reloverevolt

Добавил эндпоинт /payments/get-status/
по тз https://manzoni.atlassian.net/browse/DR-125

Комментарии:

вместо предложенного формата:
Post запрос
body: { chain: "DUC"|"DUCX"|"ETH"|"BTC", network: "mainnet"|"testnet", txs: string[] }
упростил до:

body: { tx_hashes: string[] }

так как для проверки транзакций достаточно tx_hash оставил его, а для того чтобы ориентироваться в какой сети находимся овет содержит в себе ключ is_testnet который подтягивается из переменной IS_TESTNET_PAYMENTS из settings

2021-12-13 09:19 UTC, yulian-khalitov requested changes

2021-12-13 09:19 UTC, qwdqwqdwqd commented on ducatus_exchange/payments/models.py
wtf

2021-12-13 09:19 UTC, qwdqwqdwqd commented on ducatus_exchange/payments/serializers.py
> +            'transfer_state_history')
snake_case - не по REST
давай camelCase, как в тз

2021-12-13 09:19 UTC, qwdqwqdwqd commented on ducatus_exchange/payments/serializers.py
> +        return obj.sent_amount
для простых геттеров можно использовать какой-то такой синтаксис:
https://github.com/Rock-n-Block/centurion_crowdsale_backend/blob/develop/centurion_crowdsale/projects/serializers.py#L8-L10

2021-12-13 09:19 UTC, qwdqwqdwqd commented on ducatus_exchange/payments/serializers.py
> +
адрес кошелька отправителя в бд нигде не сохраняется, так что обсудите с Олегом, нужно ли сохранять

если нужно - добавляем сохранение в базу и делаем это поле nullable (для совместимости со старыми записями)

2021-12-13 09:19 UTC, qwdqwqdwqd commented on ducatus_exchange/urls.py
> +] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
wtf 2

2021-12-13 09:19 UTC, yulian-khalitov commented on ducatus_exchange/payments/utils.py
> +    return [dict(status=status, date=dateformat.format(timezone.now(), 'Y-m-d H:i:s'))]
1. давай лучше timestamp'ом дату, на фронте там уже преобразуют куда надо
2. лучше этот метод сделать property класса, из self забирать текущий adapted статус и ничего в аргументы не передавать

2021-12-13 09:19 UTC, yulian-khalitov commented on ducatus_exchange/payments/models.py
> +    transfer_state_history = JSONField(default=generate_transfer_state_history_record, null=True, blank=True)
почему null=True?

2021-12-13 09:19 UTC, yulian-khalitov commented on ducatus_exchange/payments/urls.py
> +    path('get-status/', PaymentStatusView.as_view(), name='payments-get-status-list')
давай через snake_case, чтобы везде одинаково было

2021-12-13 09:19 UTC, yulian-khalitov commented on ducatus_exchange/payments/views.py
> +            'is_testnet': IS_TESTNET_PAYMENTS,
тебе же по тз во вьюху должен приходить флаг, тестнет не тестнет
если приходит is_testnet=true, а у тебя в конфиге IS_TESTNET_PAYMENTS=False, то нужно возвращать 403 там или 404

2021-12-13 09:24 UTC, reloverevolt commented on ducatus_exchange/payments/models.py
> +    transfer_state_history = JSONField(default=generate_transfer_state_history_record, null=True, blank=True)
Это рудимент, уберу

2021-12-13 15:27 UTC, yulian-khalitov approved these changes

2021-12-14 12:04 UTC, yulian-khalitov approved these changes

2021-12-14 12:04 UTC, merged