New scanner
MyWishPlatform/ducatus_exchange_backend pull request #64
Opened 2022-04-06 09:39 UTC by longwinterday

2022-04-06 13:16 UTC, yulian-khalitov requested changes

2022-04-06 13:16 UTC, qwdqwqdwqd commented on ducatus_exchange/settings.py
> +        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
а зочем

2022-04-06 13:16 UTC, qwdqwqdwqd commented on ducatus_exchange/transfers/tasks.py
> +            return transaction.get('confirmations') > 5
5 в конфиг в словарь сети DUC

2022-04-06 13:16 UTC, qwdqwqdwqd commented on ducatus_exchange/transfers/tasks.py
> +            return (total_block_number - transaction_block_number) > 5
5 в конфиг в словарь сети DUCX

2022-04-06 13:16 UTC, yulian-khalitov commented on ducatus_exchange/payments/tasks.py
> +def parse_logs():
```suggestion
def process_payments():
```

2022-04-06 13:16 UTC, yulian-khalitov commented on ducatus_exchange/payments/tasks.py
> +def parse_logs():
```suggestion
def process_payments():
```

2022-04-06 13:16 UTC, yulian-khalitov commented on docker-compose.yml
> +    tty: true
а зачем?

2022-04-06 13:16 UTC, yulian-khalitov commented on docker-compose.yml
> +    image: scanner:latest
нужно тут тянуть с докерхаба рнб

такая ссылка будет работать только если сначала спуллить рнб образ руками и тэгнув его scanner.

чтобы докер-компоуз спуллил сам нужно указывать полный путь с организацией

2022-04-06 13:16 UTC, yulian-khalitov commented on ducatus_exchange/parity_interface.py
> +        return int(self.eth_getTransactionByHash(tx_hash).get('blockNumber'), 16)
почему функция называется get_transaction, а возвращает только блок? надо либо переименовать, либо возвращать весь словарь

2022-04-06 13:43 UTC, longwinterday commented on ducatus_exchange/parity_interface.py
> +        return int(self.eth_getTransactionByHash(tx_hash).get('blockNumber'), 16)
Done!

2022-04-06 13:44 UTC, longwinterday commented on ducatus_exchange/payments/tasks.py
> +def parse_logs():
Done!

2022-04-11 14:03 UTC, yulian-khalitov requested changes

2022-04-11 14:03 UTC, qwdqwqdwqd commented on ducatus_exchange/scanner/views.py
> +                return Response(status=status.HTTP_204_NO_CONTENT)
```suggestion
            try:
                exchange = ExchangeRequest.objects.get(**filter_data)
            except ExchangeRequest.DoesNotExist:
                return Response(status=status.HTTP_204_NO_CONTENT)
```

2022-04-11 14:03 UTC, qwdqwqdwqd commented on ducatus_exchange/parity_interface.py
> +    def get_block_for_transfer(self, tx_hash):
что за нейминг? эта штука возвращает номер блока, в котором была транзакция, а не блок для трансфера

2022-04-11 14:03 UTC, yulian-khalitov commented on docker-compose.yml
> +    command: bash -c "python scanner/db_init.py && python scanner/main.py"
команду нужно добавить в докерфайл сканера, а отсюда убрать

2022-04-11 14:38 UTC, yulian-khalitov approved these changes

2022-04-11 14:39 UTC, merged